In [6]:
%tensorflow_version 1.x

TensorFlow is already loaded. Please restart the runtime to change versions.


# Calculo	Peso	Neurônio	Artificial	- TensoFlow

• Calcule	o	produto	escalar	do	seguintes	neurônios:

• N1	=	entradas:	13,	-5,	2,	6.	Pesos:	0.3,	0.1,	0.8,	0.5

• N2	=	entradas:	3,	-1,	9.	Pesos:	0.1,	0.7,	0.5

• N3	=	entradas:	-2,	-5,	3,	9.	Pesos:	0.4,	0.2,	0.7,	0.4

In [7]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.2


In [0]:
n1_in    = tf.constant([13.0,-5.0,2.0,6.0], name = "entrada1")
n1_p     = tf.constant([0.3,0.1,	0.8,0.5], name = "peso1")
mult     = tf.multiply(n1_in, n1_p)
Escalar1 = tf.reduce_sum(mult)

In [12]:
with tf.Session() as sess:
  print(sess.run(n1_in))
  print("\n")
  print(sess.run(n1_p))
  print("\n")
  print(sess.run(mult))
  print("\n")
  print(sess.run(Escalar1))

[13. -5.  2.  6.]


[0.3 0.1 0.8 0.5]


[ 3.9 -0.5  1.6  3. ]


8.0


In [0]:
n2_in    = tf.constant([3.0,	-1.0,	9.0], name = "entrada2")
n2_p     = tf.constant([0.1,	0.7,	0.5], name = "peso2")
mult     = tf.multiply(n2_in, n2_p)
Escalar2 = tf.reduce_sum(mult)

In [15]:
with tf.Session() as sess:
  print(sess.run(n2_in))
  print("\n")
  print(sess.run(n2_p))
  print("\n")
  print(sess.run(mult))
  print("\n")
  print(sess.run(Escalar2))

[ 3. -1.  9.]


[0.1 0.7 0.5]


[ 0.3 -0.7  4.5]


4.1


In [0]:
n3_in    = tf.constant([-2.0,	-5.0,	3.0,	9.0], name = "entrada3")
n3_p     = tf.constant([	0.4,	0.2,	0.7,	0.4], name = "peso3")
mult     = tf.multiply(n3_in, n3_p)
Escalar3 = tf.reduce_sum(mult)

In [19]:
with tf.Session() as sess:
  print(sess.run(n3_in))
  print("\n")
  print(sess.run(n3_p))
  print("\n")
  print(sess.run(mult))
  print("\n")
  print(sess.run(Escalar3))

[-2. -5.  3.  9.]


[0.4 0.2 0.7 0.4]


[-0.8       -1.         2.1        3.6000001]


3.9
