In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


# PlaceHolders
• Crie	um	placeholder que	receba	dados	do	tipo	float,	e	que	tenha	o	
formato	de	matriz	2x5.

• Crie	uma	matriz	2x5	utilizando	os	métodos	linspace e	reshape.

• Com	esses	dados	faça	uma	operação	de	divisão	por	4	dos	valores	
contidos	no	placeholder.

• Altere	a	operação	de	divisão	por	subtração,	e	subtraia	do	placeholder
o	valor	20.

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.2


In [0]:
ph = tf.placeholder(float, [2,5])

In [13]:
array  = np.linspace(1,10,10)
dados = np.reshape(array,[2,5])
print(dados)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [0]:
op = ph/4

In [16]:
with tf.Session() as sess:
  result = sess.run(op,feed_dict = {ph : dados})
  print(result)

[[0.25 0.5  0.75 1.   1.25]
 [1.5  1.75 2.   2.25 2.5 ]]


In [0]:
op = ph-20

In [18]:
with tf.Session() as sess:
  result = sess.run(op,feed_dict = {ph : dados})
  print(result)

[[-19. -18. -17. -16. -15.]
 [-14. -13. -12. -11. -10.]]


• Crie	um	placeholder que	receba	dados	do	tipo	float,	e	que	tenha	o	
formato	de	matriz	3	X None.

• Crie	uma	matriz	3	X None utilizando	os	métodos	linspace e	reshape.

• Com	esses	dados	faça	uma	operação	de	multiplicação	por	2	dos	
valores	contidos	no	placeholder.

In [0]:
ph = tf.placeholder(float, [3,None])

In [34]:
array  = np.linspace(1,30,30)
dados = np.reshape(array,[3,10])
print(dados)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]


In [0]:
op = ph*2

In [36]:
with tf.Session() as sess:
  result = sess.run(op,feed_dict = {ph : dados})
  print(result)

[[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
 [22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]
 [42. 44. 46. 48. 50. 52. 54. 56. 58. 60.]]
