# Quem estiver usando COLAB

In [1]:
from google.colab import drive
# Montar o Google Drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [18]:
# lib de estrutura e análise de dados.
import pandas as pd
# importa database em um arquivo .csv (necessário indicar o diretório)
base = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Aula 4/TopTracksSpotify2017.csv')
# exibe os valores
base.head()

id  ... time_signature
0  7qiZfU4dY1lWllzX7mPBI  ...            4.0
1  5CtI0qwDJkDQGwXD1H1cL  ...            4.0
2  4aWmUDTfIPGksMNLV2rQP  ...            4.0
3  6RUKPb4LETWmmr3iAEQkt  ...            4.0
4  3DXncPQOG4VBw3QHh3S81  ...            4.0

[5 rows x 16 columns]

# Quem estiver usando ANACONDA

In [0]:
# necessário instalação de pacote pandas.
# lib de estrutura e análise de dados.
import pandas as pd
# importa database em um arquivo .csv (neste caso no mesmo diretório)
base = pd.read_csv('house_prices.csv')
# exibe os valores
base.head()

# INÍCIO TRATAMENTO DE DADOS

In [3]:
# exibe o nome das colunas
base.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [0]:
colunas_usadas = ['danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature']

In [23]:
# seleciono apenas as colunas com informações relevantes
colunas_usadas

['danceability',
 'energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'duration_ms',
 'time_signature']

In [0]:
# COLAB
base = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Aula 4/TopTracksSpotify2017.csv', usecols = colunas_usadas)

In [0]:
# anteriormente nos usamos o conceito de padronização, onde os dados foram escalonados.
# para esse exemplo vamos usar o conceito de normalização (0 - 1).
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
# inicializamos nosso scaler com os dados, retiramos o PRICE que é nosso objetivo.
base[['danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature']] = scaler_x.fit_transform(base[['danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature']])
# para cada coluna ele recebe o scaler dos valores de X.

In [27]:
# visualização dos dados normalizados
base.head()

danceability    energy       key  ...     tempo  duration_ms  time_signature
0      0.847534  0.522184  0.090909  ...  0.167892     0.384366             1.0
1      0.651719  0.800341  0.181818  ...  0.111456     0.356880             1.0
2      0.600897  0.750853  0.181818  ...  0.823537     0.353352             1.0
3      0.536622  0.493174  1.000000  ...  0.224297     0.460011             1.0
4      0.524664  0.549488  0.636364  ...  0.047322     0.693131             1.0

[5 rows x 13 columns]

In [0]:
# para o preço que seria considerado nosso Y faremos tb a normalização.
scaler_y = MinMaxScaler()
base[['danceability']] = scaler_y.fit_transform(base[['danceability']])

In [30]:
# visualização dos dados normalizados
base.head()

danceability    energy       key  ...     tempo  duration_ms  time_signature
0      0.847534  0.522184  0.090909  ...  0.167892     0.384366             1.0
1      0.651719  0.800341  0.181818  ...  0.111456     0.356880             1.0
2      0.600897  0.750853  0.181818  ...  0.823537     0.353352             1.0
3      0.536622  0.493174  1.000000  ...  0.224297     0.460011             1.0
4      0.524664  0.549488  0.636364  ...  0.047322     0.693131             1.0

[5 rows x 13 columns]

In [0]:
# na variável X nos temos os atributos previsores, logo não queremos os valores do preço nela.
X = base.drop('danceability', axis = 1) # apaga a coluna do preço.
y = base.danceability

In [32]:
# visualizar os atributos.
X.head()

energy       key  loudness  ...     tempo  duration_ms  time_signature
0  0.522184  0.090909  0.913192  ...  0.167892     0.384366             1.0
1  0.800341  0.181818  0.786896  ...  0.111456     0.356880             1.0
2  0.750853  0.181818  0.739576  ...  0.823537     0.353352             1.0
3  0.493174  1.000000  0.517648  ...  0.224297     0.460011             1.0
4  0.549488  0.636364  0.791749  ...  0.047322     0.693131             1.0

[5 rows x 12 columns]

In [33]:
# visualizar os atributos.
y.head()

0    0.847534
1    0.651719
2    0.600897
3    0.536622
4    0.524664
Name: danceability, dtype: float64

In [34]:
# ajuste dos dados para criação das classes.
previsores_colunas = colunas_usadas[1:17] # posição 0 é o preço
previsores_colunas

['energy',
 'key',
 'loudness',
 'mode',
 'speechiness',
 'acousticness',
 'instrumentalness',
 'liveness',
 'valence',
 'tempo',
 'duration_ms',
 'time_signature']

# FIM TRATAMENTO DE DADOS.

In [35]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [0]:
import tensorflow as tf

In [37]:
tf.__version__

'1.15.2'

In [0]:
# vamos criar um for para passar nossas colunas para um array que será usado com o X.
# como os valores de X são numéricos, vamos usar um feature_column.numeric.
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [40]:
# visualizar os valores das colunas.
print(colunas[2])

NumericColumn(key='loudness', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


# Separar a base de dados

Vamos separa a base entre treinamento e testes

In [0]:
# agora precisamos criar uma base para testes e outra para o treinamento, normalmente usado 30, 70.
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [42]:
# visualizar o array X de treino.
X_treinamento.shape

(70, 12)

In [43]:
# visualizar o array Y de treino.
y_treinamento.shape

(70,)

In [44]:
# visualizar o array X de teste.
X_teste.shape

(30, 12)

# FUNÇÃO DE TREINAMENTO

In [0]:
# define a função de treinamento.
# passamos as entradas dos valores X e Y que foram separados para testes.
# batch_size é definido com 32 para que o alg não carregue de uma só vez todos os dados.
# 
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, 
                                                         y = y_treinamento,
                                                         batch_size = 32, 
                                                         num_epochs = None, 
                                                         shuffle = True)

# FUNÇÃO DE TESTE

In [0]:
# define a função de teste.
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, 
                                                   y = y_teste,
                                                   batch_size = 32, 
                                                   num_epochs = 10000, 
                                                   shuffle = False)

# ALGORITMO - REGRESSÃO LINEAR

In [47]:
# função do regressor.
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpq84db5pf', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fec095d0e10>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


TREINAMENTO...

In [48]:
# com o regressor podemos fazer o treinamento.
regressor.train(input_fn=funcao_treinamento, steps = 10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpq84db5pf/mo

In [49]:
# calculo das metricas de treinamento.
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-04-28T18:33:12Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpq84db5pf/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-04-28-18:33:36
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.017598214, global_step = 10000, label/mean = 0.66980094, loss = 0.56314284, prediction/mean = 0.6600661
INFO:tensorflow:Saving 'checkpoint_path

TESTES...

In [50]:
# calculo das metricas de testes. (função de avaliação)
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-04-28T18:33:40Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpq84db5pf/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Finished evaluation at 2020-04-28-18:34:03
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.044323128, global_step = 10000, label/mean = 0.62359107, loss = 1.4183401, prediction/mean = 0.67811567
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: /tmp/tmp

In [51]:
# exibindo valores da métrica.
metricas_treinamento

{'average_loss': 0.017598214,
 'global_step': 10000,
 'label/mean': 0.66980094,
 'loss': 0.56314284,
 'prediction/mean': 0.6600661}

In [52]:
# exibindo valores da métrica. (valores para análise de resultados.)
metricas_teste

{'average_loss': 0.044323128,
 'global_step': 10000,
 'label/mean': 0.62359107,
 'loss': 1.4183401,
 'prediction/mean': 0.67811567}

PREVISÃO...

In [0]:
# função de previsão, gera os valores para cada um dos valores de X.
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle = False)

In [0]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [55]:
# exibe valores previstos.
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpq84db5pf/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.85198224], dtype=float32)},
 {'predictions': array([0.62288594], dtype=float32)},
 {'predictions': array([0.5665797], dtype=float32)},
 {'predictions': array([0.5752864], dtype=float32)},
 {'predictions': array([0.7422537], dtype=float32)},
 {'predictions': array([0.6310452], dtype=float32)},
 {'predictions': array([0.7804037], dtype=float32)},
 {'predictions': array([0.6404171], dtype=float32)},
 {'predictions': array([0.8282819], dtype=float32)},
 {'predictions': array([0.65532637], dtype=float32)},
 {'predictions': array([0.8542887], dtype=float32)},
 {'predictions': array([0.6400654], dtype=float32)},
 {'predictions': array([0.6603379], dtype=float32)},
 {'predictions': array([0.7073367], dtype=float32)},
 {'predictions': array([0.6310492], dtype=float32)},
 {'predictions': array([0.72443116], dtype=float32)},
 {'predictions': array([0.5688299], dtype=float32)},
 {'predictions': array([0.6192843], dtype=float32)},
 {'predictions': array([0.5694825], dtype=

In [56]:
# para o calculo do erro, vamos criar um array, que irá receber cada um dos valores gerados pela função previsão.
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpq84db5pf/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [57]:
# exibe array com os valores.
# com esse valores iremos calcular os erros MSE e MAE.
valores_previsoes

[array([0.85198224], dtype=float32),
 array([0.62288594], dtype=float32),
 array([0.5665797], dtype=float32),
 array([0.5752864], dtype=float32),
 array([0.7422537], dtype=float32),
 array([0.6310452], dtype=float32),
 array([0.7804037], dtype=float32),
 array([0.6404171], dtype=float32),
 array([0.8282819], dtype=float32),
 array([0.65532637], dtype=float32),
 array([0.8542887], dtype=float32),
 array([0.6400654], dtype=float32),
 array([0.6603379], dtype=float32),
 array([0.7073367], dtype=float32),
 array([0.6310492], dtype=float32),
 array([0.72443116], dtype=float32),
 array([0.5688299], dtype=float32),
 array([0.6192843], dtype=float32),
 array([0.5694825], dtype=float32),
 array([0.66267145], dtype=float32),
 array([0.62840915], dtype=float32),
 array([0.7364763], dtype=float32),
 array([0.81638044], dtype=float32),
 array([0.52159953], dtype=float32),
 array([0.68060404], dtype=float32),
 array([0.72323275], dtype=float32),
 array([0.7231647], dtype=float32),
 array([0.62855995

In [0]:
# como os valores foram normalizados, precisamos desnormaliza-los.
import numpy as np
# colocar no formato de matriz.
valores_previsoes = np.asarray(valores_previsoes).reshape(-1,1)

In [59]:
valores_previsoes

array([[0.85198224],
       [0.62288594],
       [0.5665797 ],
       [0.5752864 ],
       [0.7422537 ],
       [0.6310452 ],
       [0.7804037 ],
       [0.6404171 ],
       [0.8282819 ],
       [0.65532637],
       [0.8542887 ],
       [0.6400654 ],
       [0.6603379 ],
       [0.7073367 ],
       [0.6310492 ],
       [0.72443116],
       [0.5688299 ],
       [0.6192843 ],
       [0.5694825 ],
       [0.66267145],
       [0.62840915],
       [0.7364763 ],
       [0.81638044],
       [0.52159953],
       [0.68060404],
       [0.72323275],
       [0.7231647 ],
       [0.62855995],
       [0.63377136],
       [0.71856046]], dtype=float32)

In [60]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[0.85198224],
       [0.62288594],
       [0.5665797 ],
       [0.5752864 ],
       [0.7422537 ],
       [0.6310452 ],
       [0.7804037 ],
       [0.6404171 ],
       [0.8282819 ],
       [0.65532637],
       [0.8542887 ],
       [0.6400654 ],
       [0.6603379 ],
       [0.7073367 ],
       [0.6310492 ],
       [0.72443116],
       [0.5688299 ],
       [0.6192843 ],
       [0.5694825 ],
       [0.66267145],
       [0.62840915],
       [0.7364763 ],
       [0.81638044],
       [0.52159953],
       [0.68060404],
       [0.72323275],
       [0.7231647 ],
       [0.62855995],
       [0.63377136],
       [0.71856046]], dtype=float32)

In [61]:
y_teste

4     0.524664
39    0.433483
61    0.635277
9     0.713004
55    0.636771
71    0.871450
49    0.762332
97    0.707025
0     0.847534
59    0.837070
42    0.949178
84    0.857997
43    0.729447
1     0.651719
2     0.600897
19    0.778774
90    0.793722
93    0.726457
11    0.590433
80    0.692078
87    0.523169
98    0.597907
57    0.666667
66    0.083707
20    0.426009
34    0.766816
70    0.385650
99    0.000000
86    0.346786
6     0.571001
Name: danceability, dtype: float64

In [62]:
y_teste.shape

(30,)

In [63]:
y_teste2 = y_teste.values.reshape(-1,1)
y_teste2.shape

(30, 1)

In [0]:
y_teste2 = scaler_y.inverse_transform(y_teste2)

In [65]:
y_teste2

array([[0.52466368],
       [0.43348281],
       [0.63527653],
       [0.71300448],
       [0.6367713 ],
       [0.87144993],
       [0.76233184],
       [0.70702541],
       [0.84753363],
       [0.83707025],
       [0.94917788],
       [0.85799701],
       [0.72944694],
       [0.65171898],
       [0.60089686],
       [0.77877429],
       [0.79372197],
       [0.7264574 ],
       [0.59043348],
       [0.69207773],
       [0.52316891],
       [0.59790732],
       [0.66666667],
       [0.08370703],
       [0.42600897],
       [0.76681614],
       [0.38565022],
       [0.        ],
       [0.34678625],
       [0.57100149]])

In [0]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [69]:
mae

0.15964591643616638

# Conclusão
Chegamos a conclusão que nivel de dansabilidade de uma track do spotify influência diretamente no seu posicionamento das musicais mais escutas, top100, no spotify