In [1]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [25]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.15.2


In [0]:
array = np.linspace(1,100,199)

In [6]:
print(array)

[  1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5
   7.    7.5   8.    8.5   9.    9.5  10.   10.5  11.   11.5  12.   12.5
  13.   13.5  14.   14.5  15.   15.5  16.   16.5  17.   17.5  18.   18.5
  19.   19.5  20.   20.5  21.   21.5  22.   22.5  23.   23.5  24.   24.5
  25.   25.5  26.   26.5  27.   27.5  28.   28.5  29.   29.5  30.   30.5
  31.   31.5  32.   32.5  33.   33.5  34.   34.5  35.   35.5  36.   36.5
  37.   37.5  38.   38.5  39.   39.5  40.   40.5  41.   41.5  42.   42.5
  43.   43.5  44.   44.5  45.   45.5  46.   46.5  47.   47.5  48.   48.5
  49.   49.5  50.   50.5  51.   51.5  52.   52.5  53.   53.5  54.   54.5
  55.   55.5  56.   56.5  57.   57.5  58.   58.5  59.   59.5  60.   60.5
  61.   61.5  62.   62.5  63.   63.5  64.   64.5  65.   65.5  66.   66.5
  67.   67.5  68.   68.5  69.   69.5  70.   70.5  71.   71.5  72.   72.5
  73.   73.5  74.   74.5  75.   75.5  76.   76.5  77.   77.5  78.   78.5
  79.   79.5  80.   80.5  81.   81.5  82.   82.5  8

In [0]:
a = tf.constant([12,	4,	46,	76,	18], name = 'a')

In [0]:
b= tf.constant(	[-10,	21,	0,	19,	99], name = 'b')

In [9]:
print(a,b)

Tensor("a:0", shape=(5,), dtype=int32) Tensor("b:0", shape=(5,), dtype=int32)


In [0]:
soma = a + b

In [22]:
with tf.Session() as sess:
  print(sess.run(soma))

[  2  25  46  95 117]


In [0]:
# Codigo para rodar no tensorflow 2.0
# tf.compat.v1.disable_eager_execution()
# sess =  tf.compat.v1.Session() 
# print(sess.run(soma))

In [0]:
array1 = tf.constant([[1,2],[0,1]])

In [0]:
array2 = tf.constant([[4,-1],[5,0]])

In [0]:
mul = tf.matmul(array2,array1)

In [30]:
with tf.Session() as sess:
  print(sess.run(array1))
  print('\n')
  print(sess.run(array2))
  print('\n')
  print(sess.run(mul))

[[1 2]
 [0 1]]


[[ 4 -1]
 [ 5  0]]


[[ 4  7]
 [ 5 10]]
