# Exemplo de implementação de rede neural low-level.
Base de dados utilizada iris do lib sklearn.

Problema multi-classes utilizando a função de ativação SOFTMAX


In [1]:
# importação da lib sklearn importando os datasets
# repositório: archive.ics.uci.edu/ml/datasets/Iris
from sklearn import datasets
import numpy as np
# vamos usar o exemplo iris()
wine = datasets.load_wine()
# atributos previsores (4 características)
X = wine.data
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [2]:
# atributos das classes
y = wine.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [20]:
# padronização dos dados
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X = np.float32(X)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 2, 1)
X =  np.delete(X, 3, 1)
X =  np.delete(X, 2, 1)
# Alcohol Malic acid Color intensity Proline
X

array([[ 1.5186125 , -0.5622498 ,  1.8479196 ,  1.013009  ],
       [ 0.24628963, -0.49941337,  1.1134493 ,  0.9652415 ],
       [ 0.19687903,  0.02123125,  0.78858745,  1.3951482 ],
       [ 1.6915497 , -0.34681064,  1.1840714 ,  2.3345737 ],
       [ 0.29570022,  0.22769377,  0.44960117, -0.03787401],
       [ 1.4815546 , -0.51736665,  0.33660576,  2.239039  ],
       [ 1.716255  , -0.4186237 ,  1.367689  ,  1.72952   ],
       [ 1.3086175 , -0.16727802,  1.367689  ,  1.7454425 ],
       [ 2.2597716 , -0.62508625,  0.33660576,  0.94931906],
       [ 1.0615644 , -0.8854085 ,  1.3253157 ,  0.94931906],
       [ 1.358028  , -0.15830138,  0.78858745,  2.4301085 ],
       [ 1.3827333 , -0.76871234,  0.29423246,  1.6976751 ],
       [ 0.92568535, -0.54429656,  0.4072279 ,  1.8250549 ],
       [ 2.1609504 , -0.54429656,  0.16711262,  1.2836909 ],
       [ 1.7039022 , -0.4186237 ,  0.54847217,  2.547935  ],
       [ 0.77745354, -0.4724835 ,  0.37897903,  1.7932099 ],
       [ 1.6050811 , -0.

![alt text](https://drive.google.com/uc?id=1bCs3lSCjjfJet-cQhoRIvgvXshAE--Rz)

Como nosso exemplo tem 3 classes como resposta, precisamos de 3 neurônios de saída

In [4]:
# precisamos compatibilizar o numero de registros de saída com a quantidade de classes esperadas.
# para isso iremos utilizar o comando OneHotEncoder para que cada resposta tenha 3 atributos, que seja igual 
# a quantidade de neurônios na camada de saída.
from sklearn.preprocessing import OneHotEncoder
# passo como parametrao qual coluna quermos fazer a transformação.
# instancio um objeto.
onehot = OneHotEncoder()
y.shape

(178,)

In [5]:
# transformando a resposta em formato de matriz
y = y.reshape(-1,1)
y.shape

(178, 1)

In [6]:
onehot.fit(y)
y = onehot.transform(y).toarray()
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

# agora temos as 3 classes representadas por codificação
classe 1 -> 1 0 0

classe 2 -> 0 1 0

classe 3 -> 0 0 1

In [0]:
# divisão da base em treinamento (70%) e teste (30%).
from sklearn.model_selection import train_test_split

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [8]:
# conferindo a quantidade de regitros.
X_treinamento.shape

(124, 13)

In [9]:
# conferindo a quantidade de regitros.
X_teste.shape

(54, 13)

In [10]:
# importação do TensorFlow
%tensorflow_version 1.x
import tensorflow as tf
# importação do NumPy
import numpy as np
tf.__version__

TensorFlow 1.x selected.


'1.15.2'

In [11]:
# quantidade dos neurônios
# para a entrada o num. de neurônios é a quantidade de atributos.
neuronios_entrada = X.shape
neuronios_entrada

(178, 13)

In [12]:
# para a camada oculta
# podemos criar a quantidade baseado no calculo
# (quantidade de atributos previsores + quantidade de classes) / 2
# np.ceil arredonda para cima
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

8

In [13]:
# neurônios na camada de saída que é igual ao num. de classes
neuronios_saida = y.shape[1]
neuronios_saida

3

![Modelo de RNA](https://drive.google.com/uc?id=1bCs3lSCjjfJet-cQhoRIvgvXshAE--Rz)

Modelo da RNA
<!-- ![Modelo da RNA](RNA2.png) -->

In [0]:
# criar os pesos, usamos uma estrutura de dados com keys
# para a camada oculta precisamos de uma matriz de 4 x 4 = 16 pesos.
# para a camada saída precisamos de uma matriz de 4 x 3 = 12 pesos.
# os valores do peso são criados com a função RANDOM.

W = {'oculta': tf.Variable(tf.random_normal([4, 4])),
    'saida': tf.Variable(tf.random_normal([4, neuronios_saida]))}

In [0]:
# pesos para a unidade de bias
# para a camada oculta teremos 4 pesos
# para a camada saída teremos 3 pesos.
b = {'oculta': tf.Variable(tf.random_normal([4])),
     'saida': tf.Variable(tf.random_normal([neuronios_saida]))}

![Modelo da RNA](https://drive.google.com/uc?id=1_-_xgpimyQ-R1TReFQrN0k7c3RjqDE28)



In [0]:
# criamos os places holders para X, com quantidade indefinida de linha e com 4 colunas
xph = tf.placeholder('float', [None, 4])
# criamos os places holders para Y, com quantidade indefinida de linha e com 3 colunas
yph = tf.placeholder('float', [None, neuronios_saida])

In [0]:
# criamos um função para facilitar na reutilização do códigos para testes.
# nesta função faremos os calculos do somatório dos peso, o calculo da função de ativação
# para as camadas da nossa rede.
def funRNA(x, W, bias):
    # somatório da camada oculta
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta']) 
    # calculo func. ativação RELU
    camada_oculta_ativacao = tf.nn.relu(camada_oculta) 
    # somatório da camada de saída.
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida']) 
    # retorno dos valores da camada oculta.
    return camada_saida

In [0]:
# criamos um modelo que irá enviar como parametros para a func. os valores de pesos e as entradas da rede.
# esperamos como saída o calculo dos valores do somatório da camada de saída.
modelo = funRNA(xph, W, b)

In [0]:
# aqui faremos o calculo da função de ativação junto com o calculo do erro.
# estamos usando a função SOFTMAX como função de ativação neste modelo.
# para que a função faça o calculo do erro, precisamos passar como paramentros os valores
# que foram calculados pela rede (modelo) e os valores corretor (yph)
# modelo -> respostas que o modelo fez a previsão
# yph -> respostas corretas, vetor Y.
# func. reduce_mean faz a média do batch inteiro.
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
# vamos criar o otimizados, usando a função ADAM, que é similar ao gradiente de descida.
# passamos como parametro o erro, para que seja feita a otimização desse erro.
otimizador = tf.train.AdamOptimizer(learning_rate = 0.01).minimize(erro)

In [66]:
# tamanho da atualização dos registros.
batch_size = 8
batch_total = int(len(X_treinamento) / batch_size)
batch_total

15

In [67]:
# separa o vetor treinamento em 13 partes.
X_batches = np.array_split(X_treinamento, batch_total)
X_batches

[array([[ 0.7898062 ,  0.685502  ,  1.0569516 ,  0.3124203 ],
        [-1.1372072 , -0.849502  ,  0.8168363 , -1.1524469 ],
        [ 0.8886274 , -0.8135955 ,  0.3648546 ,  1.7135975 ],
        [-1.9154241 ,  0.05713777,  1.0993248 , -0.3881683 ],
        [-0.08723191,  0.42517966, -0.42611337, -0.46778065],
        [ 0.29570022,  0.22769377,  0.44960117, -0.03787401],
        [-1.458376  , -0.55327314, -0.2424958 , -1.056912  ],
        [-0.7789803 , -1.0469879 ,  1.2264447 , -0.7543851 ],
        [ 1.5062599 , -0.5712264 ,  0.98632944,  0.710482  ]],
       dtype=float32),
 array([[ 0.28334758,  0.8650346 , -1.5560676 , -0.22894363],
        [ 0.5056953 ,  1.3497727 ,  0.54847217,  0.9174741 ],
        [ 0.690985  , -0.54429656,  0.59084547,  1.1881561 ],
        [-1.7054291 , -0.31090412,  0.49197447, -1.2798265 ],
        [-0.22311106,  0.92787105, -1.2170813 , -0.19709869],
        [ 0.92568535, -0.54429656,  0.4072279 ,  1.8250549 ],
        [-0.49486935,  0.11099756, -1.4571966 

In [60]:
# visualizando os valores do batch
X_batches[1] 

array([[ 0.28334758,  0.8650346 , -1.5560676 , -0.22894363],
       [ 0.5056953 ,  1.3497727 ,  0.54847217,  0.9174741 ],
       [ 0.690985  , -0.54429656,  0.59084547,  1.1881561 ],
       [-1.7054291 , -0.31090412,  0.49197447, -1.2798265 ],
       [-0.22311106,  0.92787105, -1.2170813 , -0.19709869],
       [ 0.92568535, -0.54429656,  0.4072279 ,  1.8250549 ],
       [-0.49486935,  0.11099756, -1.4571966 , -0.16525376],
       [ 0.9627433 ,  0.3802965 , -1.3159523 , -0.42001325],
       [ 0.7156903 ,  0.21871714, -1.1464592 ,  0.0098934 ]],
      dtype=float32)

# Inicio do treinamento

In [68]:
# criamos uma sessão para inicializar o treinamento.
with tf.Session() as sess:
    # inicialização das variaveis.
    sess.run(tf.global_variables_initializer())
    # definimos o numero de épocas
    for epoca in range(3000):
        # variavel para calculo do erro.
        erro_medio = 0.0
        batch_total = int(len(X_treinamento) / batch_size)
        X_batches = np.array_split(X_treinamento, batch_total)
        # separamos batchs para o Y também
        y_batches = np.array_split(y_treinamento, batch_total)
        # calculamos e ajustamos os pesos para cada posição dos registros que separamos
        for i in range(batch_total):
            # pegamos os valores dos vetores x_batches e y_batches
            X_batch, y_batch = X_batches[i], y_batches[i]
            # passamos valores para os placeholders
            # rodamos nosso otimizador, e esperamos o valor do erro.            
            _, custo = sess.run([otimizador, erro], feed_dict = {xph: X_batch, yph: y_batch})
            # calculo do erro médio
            erro_medio += custo / batch_total
        # exibimos os valores do erro para cada 500 registros.
        if epoca % 500 == 0:
            print('Época: ' + str((epoca + 1)) + ' erro: ' + str(erro_medio))
    # ao final do num. de épocas, temos os valores dos pesos ajustados.
    W_final, b_final = sess.run([W, b])

Época: 1 erro: 3.373513380686442
Época: 501 erro: 0.052057043643738636
Época: 1001 erro: 0.02375864977312929
Época: 1501 erro: 0.02333520614300563
Época: 2001 erro: 0.0231184438911131
Época: 2501 erro: 0.02300269340467504


In [32]:
# visualizando o vetor de pesos.
W_final

{'oculta': array([[ 0.8230233 , -1.0584353 ,  1.5014167 ,  0.3822117 ],
        [ 0.24816044, -0.39402783,  0.60707325,  0.54709375],
        [ 1.4088385 , -0.55796814, -0.09997141, -1.9124062 ],
        [ 0.03997169, -2.2297235 ,  0.8591039 , -0.06184371]],
       dtype=float32), 'saida': array([[ 2.0204747 , -0.8584542 , -1.1295006 ],
        [-1.4435753 ,  1.0291214 ,  0.00931376],
        [ 0.629079  , -1.4336834 , -1.2419999 ],
        [-1.8616393 , -0.41132447,  1.8652508 ]], dtype=float32)}

In [33]:
# visualizando o vetor de bias.
b_final

{'oculta': array([-1.6394377 ,  1.3632499 ,  0.47001785,  0.36261082], dtype=float32),
 'saida': array([ 1.2646803 ,  1.0326518 , -0.44468436], dtype=float32)}

# Previsões

com os valores de pesos ajustados, pordemo fazer algumas previsões.

In [0]:
# passamos para a func. previsões, os valores de pesos ajustados.
previsoes_teste = funRNA(xph, W_final, b_final)
with tf.Session() as sess:
    # inicializamos as variaveis.
    sess.run(tf.global_variables_initializer())
    # vamos executar a func. previsões, passando o vetor de teste como um placeholder.
    resp = sess.run(previsoes_teste, feed_dict = {xph: X_teste})
    # para o retorno da probabilidade de cada saída, excutamos a func. softmax.
    probabilidade = sess.run(tf.nn.softmax(resp))
    # para facilitar a visualização dos valores, vamos usar a func. argmax que retorna
    # o indice de onde esta o maior numero.
    resp_final = sess.run(tf.argmax(probabilidade, 1))

In [37]:
# visualizamos as previsões em percentual.
probabilidade

array([[5.70234079e-06, 9.93215561e-01, 6.77884091e-03],
       [5.15369233e-04, 7.48361170e-01, 2.51123458e-01],
       [9.70609248e-01, 2.42122263e-03, 2.69694757e-02],
       [9.99940634e-01, 1.72910211e-06, 5.75828672e-05],
       [9.31665361e-01, 1.39535321e-02, 5.43810539e-02],
       [5.17969802e-02, 7.09523201e-01, 2.38679737e-01],
       [1.17156897e-02, 8.45008731e-01, 1.43275559e-01],
       [9.99898076e-01, 1.46905768e-05, 8.73054378e-05],
       [9.62979198e-01, 5.15600992e-03, 3.18647102e-02],
       [3.55561674e-02, 7.52828479e-01, 2.11615339e-01],
       [9.58272278e-01, 6.39719330e-03, 3.53306383e-02],
       [9.99991417e-01, 1.51139534e-06, 7.00020792e-06],
       [8.80157022e-05, 2.66911574e-02, 9.73220825e-01],
       [9.99318957e-01, 7.23839621e-05, 6.08643342e-04],
       [1.35163809e-05, 1.01913558e-03, 9.98967409e-01],
       [9.89920139e-01, 1.36298139e-03, 8.71691480e-03],
       [5.98733546e-03, 8.82574260e-01, 1.11438371e-01],
       [3.51684264e-08, 4.54379

In [72]:
# visualizamos a resposta do maior percentual para cada resposta.
resp_final

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 1, 2, 1, 0, 0, 2,
       2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 0, 1, 2,
       1, 0, 2, 1, 0, 2, 0, 2, 2, 1])

# Avaliação da rede.

In [73]:
# para iniciar o calculo precisamos compatibilizar as respostas
# para isso utilizaremos a func. argmax no vetor de resultados também.
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0, 2, 0, 1, 2, 1, 0, 0, 2,
       2, 1, 2, 1, 1, 1, 0, 2, 0, 2, 0, 1, 0, 2, 2, 0, 2, 1, 1, 0, 1, 2,
       1, 0, 2, 2, 0, 2, 0, 2, 2, 1])

# Resultado
Com 4 entradas: Alcohol Malic acid Color intensity Proline.<br>
Conseguimos chegar em uma taxa de acerto de 96,3%, isso quer dizer que no rede neural consegue reconhecer vinhos por esses 4 parametros e com 96% de acerto utilizando a função de ativação de Softmax. Com um otimizador de erro de learning_rate = 0.0001
<br>
<br>
% de outras f de Ativação:

> Softmax - Acerto = 96,3% -
learning_rate = 0.0001

> Sigmoid - Acerto = 68,5% -
learning_rate = 0.0001

> Sigmoid - Acerto = 50% -
learning_rate = 0.000001

> Sigmoid - Acerto = 90,7% -
learning_rate = 0.01

> Softmax - Acerto = 85,15% -
learning_rate = 0.01











In [74]:
# para o calculo de precisão vamos usar a func. accuracy_score do sklearn.
from sklearn.metrics import accuracy_score
# calculo de precisão da rede
taxa_acerto = accuracy_score(y_teste2, resp_final)
# valor em %
taxa_acerto

0.8518518518518519